version: '3.8'

services:
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: yourdb
      MYSQL_USER: youruser
      MYSQL_PASSWORD: yourpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - review-chatbot-network

  backend:
    build:
      context: ./backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_USER=youruser
      - DB_PASSWORD=yourpassword
      - DB_NAME=yourdb
    networks:
      - review-chatbot-network
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    networks:
      - review-chatbot-network

  migrate:
    image: migrate/migrate:v4.15.2
    volumes:
      - ./migrations:/migrations
    entrypoint: ["/bin/sh", "-c", "migrate -path /migrations -database 'mysql://youruser:yourpassword@tcp(db:3306)/yourdb' up"]
    depends_on:
      - db
    networks:
      - review-chatbot-network

networks:
  review-chatbot-network:
    driver: bridge

volumes:
  db_data:
